### ISSUE TITLE
Put CvGameCoreDLL in own repo?

### ISSUE THREAD

**Issue by RafiKueng** [civ4-mp/pbmod#1]
How about outsourcing the CvGameCoreDLL in it's own repo and have here in the mod repo only the compiled dll? One might do a versioned release of the dll, once some changes are tested and good to go, and then include the binary / dll here for the mod.

I already did it on some forks, but if my help is wanted here, I'd glad to contribute upstream.

**Comment by YggdrasiI** [comment]
Hello Rafi,

I didn't like the idea to split the code base and shifting away/hide the C++ parts. 
After such split it would be harder to track which Python change also requires changes in the C++ wrapper classes, etc.
If other modders had included 'pbmod changes' into their code base they need to track two repos after a split.

Well, I agree that the structure (mod to install is just a subfolder) made it more difficult to distribute the mod to players.
And I also dislike the current fact that the compiled DLL is part of the repo because it blows up the repo size for no reason.

How did you mange the merge of pbmod code into your forks? 

In my opinion the best compromise/solution would be:
• Remove compiled DLL from this repo (-> copy of PBMod_v10 mod folder not working anymore)
• Using release-feature of Github for providing Zip-Archives of the mod subfolder (+ compiled DLL)
